version: "3.7"

x-app: &base-app
  build:
    context: .
    target: app
  depends_on:
    - database
  volumes:
    - ./src:/app/src
    - ./tests:/app/tests
    - ./deploy:/app/deploy
    - ./pyproject.toml:/app/pyproject.toml
    - ./fixtures:/app/fixtures
  environment: &base-app-env
    SECRET_KEY: "insecure"
    DEBUG: 0
    PYTHONBREAKPOINT:
    CORS_DEFAULT_ALLOWED_ORIGIN: "http://localhost:8080"
    UVICORN_CMD_ARGS: '--reload'
  entrypoint: /app/deploy/wait-for-it.sh database:5432 --

services:
  database:
    image: timescale/timescaledb-postgis:latest-pg12
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev

  dev:
    <<: *base-app
    build:
      context: .
      target: dev
    environment:
      <<: *base-app-env
      DEBUG: "true"
    command: python manage.py runserver_plus --print-sql 0.0.0.0:8000

  app:
    <<: *base-app
    build:
      context: .
      target: app
      args:
        - BUILD_DATE
        - BUILD_REVISION
        - BUILD_VERSION
    image: taoregistry.azurecr.io/azure-aks-django:${VERSION:-latest}
    command: /app/deploy/run.sh

  test:
    <<: *base-app
    build:
      context: .
      target: tests
    environment:
      <<: *base-app-env
      DJANGO_SETTINGS_MODULE: "main.settings"
      PYTEST_ADDOPTS:
